env:
  browser: true
  es2022: true

extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier

parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module

rules:
  no-console: off
