name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_KEY }}
          scp_source: .
          scp_target: ${{ secrets.SCP_TARGET }}
          after_script: cd ${{ secrets.SCP_TARGET }} && cp ~/.config/.env.discord-bot .env && docker compose up --build -d
